-define(METRICS_DEF, [{new_gauge, 'bytes/received'},
                  {new_gauge, 'bytes/sent'},
                  {new_gauge, 'messages/dropped'},
                  {new_gauge, 'messages/qos0/received'},
                  {new_gauge, 'messages/qos0/sent'},
                  {new_gauge, 'messages/qos1/received'},
                  {new_gauge, 'messages/qos1/sent'},
                  {new_gauge, 'messages/qos2/received'},
                  {new_gauge, 'messages/qos2/sent'},
                  {new_gauge, 'messages/received'},
                  {new_gauge, 'messages/retained'},
                  {new_gauge, 'messages/sent'},
                  {new_gauge, 'packets/connack'},
                  {new_gauge, 'packets/connect'},
                  {new_gauge, 'packets/disconnect'},
                  {new_gauge, 'packets/pingreq'},
                  {new_gauge, 'packets/pingresp'},
                  {new_gauge, 'packets/puback/received'},
                  {new_gauge, 'packets/puback/sent'},
                  {new_gauge, 'packets/pubcomp/received'},
                  {new_gauge, 'packets/pubcomp/sent'},
                  {new_gauge, 'packets/publish/received'},
                  {new_gauge, 'packets/publish/sent'},
                  {new_gauge, 'packets/pubrec/received'},
                  {new_gauge, 'packets/pubrec/sent'},
                  {new_gauge, 'packets/pubrel/received'},
                  {new_gauge, 'packets/pubrel/sent'},
                  {new_gauge, 'packets/received'},
                  {new_gauge, 'packets/sent'},
                  {new_gauge, 'packets/suback'},
                  {new_gauge, 'packets/subscribe'},
                  {new_gauge, 'packets/unsuback'},
                  {new_gauge, 'packets/unsubscribe'}]).

-define(METRICS, [Name || {_, Name} <- ?METRICS_DEF]).

-define(INTERVAL_1, 60 * 1000 * 1).  %% 1 minutes interval, data merging
-define(INTERVAL_2, 60 * 1000 * 15). %% 15 minutes interval, data merging
-define(INTERVAL_3, 60 * 1000 * 60). %% 60 minutes interval, data merging

-define(METRICS_TABS, ['bytes/received',
                  'bytes/sent',
                  'messages/dropped',
                  'messages/qos0/receid',
                  'messages/qos0/sent',
                  'messages/qos1/received',
                  'messages/qos1/sent',
                  'messages/qos2/received',
                  'messages/qos2/sent',
                  'messages/received',
                  'messages/retained',
                  'messages/sent',
                  'packets/connack',
                  'packets/connect',
                  'packets/disconnect',
                  'packets/pingreq',
                  'packets/pingresp',
                  'packets/puback/received',
                  'packets/puback/sent',
                  'packets/pubcomp/received',
                  'packets/pubcomp/sent',
                  'packets/publish/received',
                  'packets/publish/sent',
                  'packets/pubrec/received',
                  'packets/pubrec/sent',
                  'packets/pubrel/received',
                  'packets/pubrel/sent',
                  'packets/received',
                  'packets/sent',
                  'packets/suback',
                  'packets/subscribe',
                  'packets/unsuback',
                  'packets/unsubscribe',

                  'bytes/received/1',
                  'bytes/sent/1',
                  'messages/dropped/1',
                  'messages/qos0/receid/1',
                  'messages/qos0/sent/1',
                  'messages/qos1/received/1',
                  'messages/qos1/sent/1',
                  'messages/qos2/received/1',
                  'messages/qos2/sent/1',
                  'messages/received/1',
                  'messages/retained/1',
                  'messages/sent/1',
                  'packets/connack/1',
                  'packets/connect/1',
                  'packets/disconnect/1',
                  'packets/pingreq/1',
                  'packets/pingresp/1',
                  'packets/puback/received/1',
                  'packets/puback/sent/1',
                  'packets/pubcomp/received/1',
                  'packets/pubcomp/sent/1',
                  'packets/publish/received/1',
                  'packets/publish/sent/1',
                  'packets/pubrec/received/1',
                  'packets/pubrec/sent/1',
                  'packets/pubrel/received/1',
                  'packets/pubrel/sent/1',
                  'packets/received/1',
                  'packets/sent/1',
                  'packets/suback/1',
                  'packets/subscribe/1',
                  'packets/unsuback/1',
                  'packets/unsubscribe/1',

                  'bytes/received/2',
                  'bytes/sent/2',
                  'messages/dropped/2',
                  'messages/qos0/receid/2',
                  'messages/qos0/sent/2',
                  'messages/qos1/received/2',
                  'messages/qos1/sent/2',
                  'messages/qos2/received/2',
                  'messages/qos2/sent/2',
                  'messages/received/2',
                  'messages/retained/2',
                  'messages/sent/2',
                  'packets/connack/2',
                  'packets/connect/2',
                  'packets/disconnect/2',
                  'packets/pingreq/2',
                  'packets/pingresp/2',
                  'packets/puback/received/2',
                  'packets/puback/sent/2',
                  'packets/pubcomp/received/2',
                  'packets/pubcomp/sent/2',
                  'packets/publish/received/2',
                  'packets/publish/sent/2',
                  'packets/pubrec/received/2',
                  'packets/pubrec/sent/2',
                  'packets/pubrel/received/2',
                  'packets/pubrel/sent/2',
                  'packets/received/2',
                  'packets/sent/2',
                  'packets/suback/2',
                  'packets/subscribe/2',
                  'packets/unsuback/2',
                  'packets/unsubscribe/2',

                  'bytes/received/3',
                  'bytes/sent/3',
                  'messages/dropped/3',
                  'messages/qos0/receid/3',
                  'messages/qos0/sent/3',
                  'messages/qos1/received/3',
                  'messages/qos1/sent/3',
                  'messages/qos2/received/3',
                  'messages/qos2/sent/3',
                  'messages/received/3',
                  'messages/retained/3',
                  'messages/sent/3',
                  'packets/connack/3',
                  'packets/connect/3',
                  'packets/disconnect/3',
                  'packets/pingreq/3',
                  'packets/pingresp/3',
                  'packets/puback/received/3',
                  'packets/puback/sent/3',
                  'packets/pubcomp/received/3',
                  'packets/pubcomp/sent/3',
                  'packets/publish/received/3',
                  'packets/publish/sent/3',
                  'packets/pubrec/received/3',
                  'packets/pubrec/sent/3',
                  'packets/pubrel/received/3',
                  'packets/pubrel/sent/3',
                  'packets/received/3',
                  'packets/sent/3',
                  'packets/suback/3',
                  'packets/subscribe/3',
                  'packets/unsuback/3',
                  'packets/unsubscribe/3'
]).

