-define(METRICS, ['bytes/received',
                  'bytes/sent',
                  'messages/dropped',
                  'messages/qos0/received',
                  'messages/qos0/sent',
                  'messages/qos1/received',
                  'messages/qos1/sent',
                  'messages/qos2/received',
                  'messages/qos2/sent',
                  'messages/received',
                  'messages/retained',
                  'messages/sent',
                  'packets/connack',
                  'packets/connect',
                  'packets/disconnect',
                  'packets/pingreq',
                  'packets/pingresp',
                  'packets/puback/received',
                  'packets/puback/sent',
                  'packets/pubcomp/received',
                  'packets/pubcomp/sent',
                  'packets/publish/received',
                  'packets/publish/sent',
                  'packets/pubrec/received',
                  'packets/pubrec/sent',
                  'packets/pubrel/received',
                  'packets/pubrel/sent',
                  'packets/received',
                  'packets/sent',
                  'packets/suback',
                  'packets/subscribe',
                  'packets/unsuback',
                  'packets/unsubscribe']).


